theme: jekyll-theme-minimal
title: San Diego Planning Database
logo: assets/logo.png
description: An extended verion of the Census Planning database for San Diego county tracts, cities and communities. 